/*
 * This source file was generated by the Gradle 'init' task
 */
package de.mixxplorer.keycloak.ssc.example;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
